services:
  dart-pipeline-streamlit:
    image: ghcr.io/dart-vietnam/dart-pipeline-gui:latest
    env_file: .env
    volumes:
      - .streamlit:/.streamlit
    ports:
      # - "8051:8051" # default port
      - "8001:8001" # from .streamlit/config.toml
